### ISSUE TITLE
input  json is null or empty error

### ISSUE THREAD

**Issue by lewisyml** [graphiq-data/pdi-fastjsoninput-plugin#12]
I get error   when  input json : 
1. {}        error 
2. null    error 
3.{
    ['id':'123', 'name':'456' ],
    ['id':'123', ]
  }    correct 

2016/10/24 12:01:46 - Fast JSON Input.0 - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : Unexpected Error : org.pentaho.di.core.exception.KettleException: 
2016/10/24 12:01:46 - Fast JSON Input.0 - Error parsing string [java.lang.IllegalArgumentException: json string can not be null or empty]!
2016/10/24 12:01:46 - Fast JSON Input.0 - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : org.pentaho.di.core.exception.KettleException: 
2016/10/24 12:01:46 - Fast JSON Input.0 - Error parsing string [java.lang.IllegalArgumentException: json string can not be null or empty]!
2016/10/24 12:01:46 - Fast JSON Input.0 - 
2016/10/24 12:01:46 - Fast JSON Input.0 - 	at com.trail2peak.pdi.fastjsoninput.FastJsonReader.readString(FastJsonReader.java:96)
2016/10/24 12:01:46 - Fast JSON Input.0 - 	at com.trail2peak.pdi.fastjsoninput.FastJsonInput.parseJson(FastJsonInput.java:312)
2016/10/24 12:01:46 - Fast JSON Input.0 - 	at com.trail2peak.pdi.fastjsoninput.FastJsonInput.readFileOrString(FastJsonInput.java:298)
2016/10/24 12:01:46 - Fast JSON Input.0 - 	at com.trail2peak.pdi.fastjsoninput.FastJsonInput.readNextString(FastJsonInput.java:190)
2016/10/24 12:01:46 - Fast JSON Input.0 - 	at com.trail2peak.pdi.fastjsoninput.FastJsonInput.getOneRow(FastJsonInput.java:448)
2016/10/24 12:01:46 - Fast JSON Input.0 - 	at com.trail2peak.pdi.fastjsoninput.FastJsonInput.processRow(FastJsonInput.java:392)
2016/10/24 12:01:46 - Fast JSON Input.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2016/10/24 12:01:46 - Fast JSON Input.0 - 	at java.lang.Thread.run(Thread.java:745)

**Comment by overtron** [comment]
What are you expecting to happen in scenarios 1&2?
